# 清除thymeleaf的缓存
spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useSSL=true&useUnicode=true&CharacterEncoding=UTF-8
    username: root
    password: uiophjklnm111
  #MailProperties
  mail:
    host: smtp.163.com
    port: 465
    username: 13275744008@163.com
    password: PAQPVQIZHJUQFBNO
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.debug: true
    default-encoding: utf-8
  aop:
    auto: true
  #RedisProperties
  redis:
    database: 11
    host: localhost
    port: 6379
  #KafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000



mybatis:
  #  指定要扫描的xxxMapper.xml
  mapper-locations: classpath:mapper/*.xml

  type-aliases-package: com.nowcoder.community.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 注:如果配置信息较多,可以考虑使用第一种

# 定义域名domain
community:
  path.domain: http://localhost:8080
  path.upload: E:\work\data\community\upload
server:
  servlet:
    context-path: "/community"